updatecli: Extract (primeRepository, primeTag) pairs for images
mikefarah yq (used on the GitHub runner and shipped in CI) does not implement
jq's `objects` filter or `if/then/else/end`

```
bash  ./updatecli/scripts/update_chart_and_images_prime.sh rancher-vsphere-csi 3.7.2-rancher400
[INFO]  updating chart rancher-vsphere-csi in charts/chart_versions.yaml
[INFO]  found version 3.7.2-rancher300, updating to 3.7.2-rancher400
[INFO]  downloading chart rancher-vsphere-csi version 3.7.2-rancher400 to extract PRIME image versions
Error: 4:15: lexer: invalid input text "objects\n        ..."
```

Signed-off-by: Michael Fritch <mfritch@suse.com>